./constants ./demos/lir/test1.lir test > ./demos/std_const_out/test1.const.out
./constants ./demos/lir/test2.lir test > ./demos/std_const_out/test2.const.out
./constants ./demos/lir/test3.lir test > ./demos/std_const_out/test3.const.out
./constants ./demos/lir/test4.lir test > ./demos/std_const_out/test4.const.out
./constants ./demos/lir/test5.lir test > ./demos/std_const_out/test5.const.out
./constants ./demos/lir/test6.lir test > ./demos/std_const_out/test6.const.out
./constants ./demos/lir/test7.lir test > ./demos/std_const_out/test7.const.out
./constants ./demos/lir/test8.lir test > ./demos/std_const_out/test8.const.out
./constants ./demos/lir/test9.lir test > ./demos/std_const_out/test9.const.out
./constants ./demos/lir/test10.lir test > ./demos/std_const_out/test10.const.out
./constants ./demos/lir/test11.lir test > ./demos/std_const_out/test11.const.out
./constants ./demos/lir/test12.lir test > ./demos/std_const_out/test12.const.out
./constants ./demos/lir/test13.lir test > ./demos/std_const_out/test13.const.out
./constants ./demos/lir/test14.lir test > ./demos/std_const_out/test14.const.out
./constants ./demos/lir/test15.lir test > ./demos/std_const_out/test15.const.out
./constants ./demos/lir/test16.lir test > ./demos/std_const_out/test16.const.out
./constants ./demos/lir/test17.lir test > ./demos/std_const_out/test17.const.out
./constants ./demos/lir/test18.lir test > ./demos/std_const_out/test18.const.out
./constants ./demos/lir/test19.lir test > ./demos/std_const_out/test19.const.out
./constants ./demos/lir/test20.lir test > ./demos/std_const_out/test20.const.out
./constants ./demos/lir/test21.lir test > ./demos/std_const_out/test21.const.out
./constants ./demos/lir/test22.lir test > ./demos/std_const_out/test22.const.out
./constants ./demos/lir/test23.lir test > ./demos/std_const_out/test23.const.out
./constants ./demos/lir/test24.lir test > ./demos/std_const_out/test24.const.out
./constants ./demos/lir/test25.lir test > ./demos/std_const_out/test25.const.out
./constants ./demos/lir/test26.lir test > ./demos/std_const_out/test26.const.out
./constants ./demos/lir/test27.lir test > ./demos/std_const_out/test27.const.out
./constants ./demos/lir/test28.lir test > ./demos/std_const_out/test28.const.out
./constants ./demos/lir/test29.lir test > ./demos/std_const_out/test29.const.out
./constants ./demos/lir/test30.lir test > ./demos/std_const_out/test30.const.out
./constants ./demos/lir/test31.lir test > ./demos/std_const_out/test31.const.out
./constants ./demos/lir/test32.lir test > ./demos/std_const_out/test32.const.out

# ./remote_constants.sh ./demos/lir/test1.lir test ./demos/std_const_out/test1.const.out
# ./remote_constants.sh ./demos/lir/test2.lir test ./demos/std_const_out/test2.const.out
# ./remote_constants.sh ./demos/lir/test3.lir test ./demos/std_const_out/test3.const.out
# ./remote_constants.sh ./demos/lir/test4.lir test ./demos/std_const_out/test4.const.out
# ./remote_constants.sh ./demos/lir/test5.lir test ./demos/std_const_out/test5.const.out
# ./remote_constants.sh ./demos/lir/test6.lir test ./demos/std_const_out/test6.const.out
# ./remote_constants.sh ./demos/lir/test7.lir test ./demos/std_const_out/test7.const.out
# ./remote_constants.sh ./demos/lir/test8.lir test ./demos/std_const_out/test8.const.out
# ./remote_constants.sh ./demos/lir/test9.lir test ./demos/std_const_out/test9.const.out
# ./remote_constants.sh ./demos/lir/test10.lir test ./demos/std_const_out/test10.const.out
# ./remote_constants.sh ./demos/lir/test11.lir test ./demos/std_const_out/test11.const.out
# ./remote_constants.sh ./demos/lir/test12.lir test ./demos/std_const_out/test12.const.out
# ./remote_constants.sh ./demos/lir/test13.lir test ./demos/std_const_out/test13.const.out
# ./remote_constants.sh ./demos/lir/test14.lir test ./demos/std_const_out/test14.const.out
# ./remote_constants.sh ./demos/lir/test15.lir test ./demos/std_const_out/test15.const.out
# ./remote_constants.sh ./demos/lir/test16.lir test ./demos/std_const_out/test16.const.out
# ./remote_constants.sh ./demos/lir/test17.lir test ./demos/std_const_out/test17.const.out
# ./remote_constants.sh ./demos/lir/test18.lir test ./demos/std_const_out/test18.const.out
# ./remote_constants.sh ./demos/lir/test19.lir test ./demos/std_const_out/test19.const.out
# ./remote_constants.sh ./demos/lir/test20.lir test ./demos/std_const_out/test20.const.out
# ./remote_constants.sh ./demos/lir/test21.lir test ./demos/std_const_out/test21.const.out
# ./remote_constants.sh ./demos/lir/test22.lir test ./demos/std_const_out/test22.const.out
# ./remote_constants.sh ./demos/lir/test23.lir test ./demos/std_const_out/test23.const.out
# ./remote_constants.sh ./demos/lir/test24.lir test ./demos/std_const_out/test24.const.out
# ./remote_constants.sh ./demos/lir/test25.lir test ./demos/std_const_out/test25.const.out
# ./remote_constants.sh ./demos/lir/test26.lir test ./demos/std_const_out/test26.const.out
# ./remote_constants.sh ./demos/lir/test27.lir test ./demos/std_const_out/test27.const.out
# ./remote_constants.sh ./demos/lir/test28.lir test ./demos/std_const_out/test28.const.out
# ./remote_constants.sh ./demos/lir/test29.lir test ./demos/std_const_out/test29.const.out
# ./remote_constants.sh ./demos/lir/test30.lir test ./demos/std_const_out/test30.const.out
# ./remote_constants.sh ./demos/lir/test31.lir test ./demos/std_const_out/test31.const.out
# ./remote_constants.sh ./demos/lir/test32.lir test ./demos/std_const_out/test32.const.out


./constants_analysis ./demos/json/test1.json test > ./demos/const_out/test1.const.out
./constants_analysis ./demos/json/test2.json test > ./demos/const_out/test2.const.out
./constants_analysis ./demos/json/test3.json test > ./demos/const_out/test3.const.out
./constants_analysis ./demos/json/test4.json test > ./demos/const_out/test4.const.out
./constants_analysis ./demos/json/test5.json test > ./demos/const_out/test5.const.out
./constants_analysis ./demos/json/test6.json test > ./demos/const_out/test6.const.out
./constants_analysis ./demos/json/test7.json test > ./demos/const_out/test7.const.out
./constants_analysis ./demos/json/test8.json test > ./demos/const_out/test8.const.out
./constants_analysis ./demos/json/test9.json test > ./demos/const_out/test9.const.out
./constants_analysis ./demos/json/test10.json test > ./demos/const_out/test10.const.out
./constants_analysis ./demos/json/test11.json test > ./demos/const_out/test11.const.out
./constants_analysis ./demos/json/test12.json test > ./demos/const_out/test12.const.out
./constants_analysis ./demos/json/test13.json test > ./demos/const_out/test13.const.out
./constants_analysis ./demos/json/test14.json test > ./demos/const_out/test14.const.out
./constants_analysis ./demos/json/test15.json test > ./demos/const_out/test15.const.out
./constants_analysis ./demos/json/test16.json test > ./demos/const_out/test16.const.out
./constants_analysis ./demos/json/test17.json test > ./demos/const_out/test17.const.out
./constants_analysis ./demos/json/test18.json test > ./demos/const_out/test18.const.out
./constants_analysis ./demos/json/test19.json test > ./demos/const_out/test19.const.out
./constants_analysis ./demos/json/test20.json test > ./demos/const_out/test20.const.out
./constants_analysis ./demos/json/test21.json test > ./demos/const_out/test21.const.out
./constants_analysis ./demos/json/test22.json test > ./demos/const_out/test22.const.out
./constants_analysis ./demos/json/test23.json test > ./demos/const_out/test23.const.out
./constants_analysis ./demos/json/test24.json test > ./demos/const_out/test24.const.out
./constants_analysis ./demos/json/test25.json test > ./demos/const_out/test25.const.out
./constants_analysis ./demos/json/test26.json test > ./demos/const_out/test26.const.out
./constants_analysis ./demos/json/test27.json test > ./demos/const_out/test27.const.out
./constants_analysis ./demos/json/test28.json test > ./demos/const_out/test28.const.out
./constants_analysis ./demos/json/test29.json test > ./demos/const_out/test29.const.out
./constants_analysis ./demos/json/test30.json test > ./demos/const_out/test30.const.out
./constants_analysis ./demos/json/test31.json test > ./demos/const_out/test31.const.out
./constants_analysis ./demos/json/test32.json test > ./demos/const_out/test32.const.out

