./intervals ./demos/lir/test1.lir test > ./demos/std_inter_out/test1.inter.out
./intervals ./demos/lir/test2.lir test > ./demos/std_inter_out/test2.inter.out
./intervals ./demos/lir/test3.lir test > ./demos/std_inter_out/test3.inter.out
./intervals ./demos/lir/test4.lir test > ./demos/std_inter_out/test4.inter.out
./intervals ./demos/lir/test5.lir test > ./demos/std_inter_out/test5.inter.out
./intervals ./demos/lir/test6.lir test > ./demos/std_inter_out/test6.inter.out
./intervals ./demos/lir/test7.lir test > ./demos/std_inter_out/test7.inter.out
./intervals ./demos/lir/test8.lir test > ./demos/std_inter_out/test8.inter.out
./intervals ./demos/lir/test9.lir test > ./demos/std_inter_out/test9.inter.out
./intervals ./demos/lir/test10.lir test > ./demos/std_inter_out/test10.inter.out
./intervals ./demos/lir/test11.lir test > ./demos/std_inter_out/test11.inter.out
./intervals ./demos/lir/test12.lir test > ./demos/std_inter_out/test12.inter.out
./intervals ./demos/lir/test13.lir test > ./demos/std_inter_out/test13.inter.out
./intervals ./demos/lir/test14.lir test > ./demos/std_inter_out/test14.inter.out
./intervals ./demos/lir/test15.lir test > ./demos/std_inter_out/test15.inter.out
./intervals ./demos/lir/test16.lir test > ./demos/std_inter_out/test16.inter.out
./intervals ./demos/lir/test17.lir test > ./demos/std_inter_out/test17.inter.out
./intervals ./demos/lir/test18.lir test > ./demos/std_inter_out/test18.inter.out
./intervals ./demos/lir/test19.lir test > ./demos/std_inter_out/test19.inter.out
./intervals ./demos/lir/test20.lir test > ./demos/std_inter_out/test20.inter.out
./intervals ./demos/lir/test21.lir test > ./demos/std_inter_out/test21.inter.out
./intervals ./demos/lir/test22.lir test > ./demos/std_inter_out/test22.inter.out
./intervals ./demos/lir/test23.lir test > ./demos/std_inter_out/test23.inter.out
./intervals ./demos/lir/test24.lir test > ./demos/std_inter_out/test24.inter.out
./intervals ./demos/lir/test25.lir test > ./demos/std_inter_out/test25.inter.out
./intervals ./demos/lir/test26.lir test > ./demos/std_inter_out/test26.inter.out
./intervals ./demos/lir/test27.lir test > ./demos/std_inter_out/test27.inter.out
./intervals ./demos/lir/test28.lir test > ./demos/std_inter_out/test28.inter.out
./intervals ./demos/lir/test29.lir test > ./demos/std_inter_out/test29.inter.out
./intervals ./demos/lir/test30.lir test > ./demos/std_inter_out/test30.inter.out
./intervals ./demos/lir/test31.lir test > ./demos/std_inter_out/test31.inter.out
./intervals ./demos/lir/test32.lir test > ./demos/std_inter_out/test32.inter.out


./intervals_analysis ./demos/json/test1.json test > ./demos/inter_out/test1.inter.out
./intervals_analysis ./demos/json/test2.json test > ./demos/inter_out/test2.inter.out
./intervals_analysis ./demos/json/test3.json test > ./demos/inter_out/test3.inter.out
./intervals_analysis ./demos/json/test4.json test > ./demos/inter_out/test4.inter.out
./intervals_analysis ./demos/json/test5.json test > ./demos/inter_out/test5.inter.out
./intervals_analysis ./demos/json/test6.json test > ./demos/inter_out/test6.inter.out
./intervals_analysis ./demos/json/test7.json test > ./demos/inter_out/test7.inter.out
./intervals_analysis ./demos/json/test8.json test > ./demos/inter_out/test8.inter.out
./intervals_analysis ./demos/json/test9.json test > ./demos/inter_out/test9.inter.out
./intervals_analysis ./demos/json/test10.json test > ./demos/inter_out/test10.inter.out
./intervals_analysis ./demos/json/test11.json test > ./demos/inter_out/test11.inter.out
./intervals_analysis ./demos/json/test12.json test > ./demos/inter_out/test12.inter.out
./intervals_analysis ./demos/json/test13.json test > ./demos/inter_out/test13.inter.out
./intervals_analysis ./demos/json/test14.json test > ./demos/inter_out/test14.inter.out
./intervals_analysis ./demos/json/test15.json test > ./demos/inter_out/test15.inter.out
./intervals_analysis ./demos/json/test16.json test > ./demos/inter_out/test16.inter.out
./intervals_analysis ./demos/json/test17.json test > ./demos/inter_out/test17.inter.out
./intervals_analysis ./demos/json/test18.json test > ./demos/inter_out/test18.inter.out
./intervals_analysis ./demos/json/test19.json test > ./demos/inter_out/test19.inter.out
./intervals_analysis ./demos/json/test20.json test > ./demos/inter_out/test20.inter.out
./intervals_analysis ./demos/json/test21.json test > ./demos/inter_out/test21.inter.out
./intervals_analysis ./demos/json/test22.json test > ./demos/inter_out/test22.inter.out
./intervals_analysis ./demos/json/test23.json test > ./demos/inter_out/test23.inter.out
./intervals_analysis ./demos/json/test24.json test > ./demos/inter_out/test24.inter.out
./intervals_analysis ./demos/json/test25.json test > ./demos/inter_out/test25.inter.out
./intervals_analysis ./demos/json/test26.json test > ./demos/inter_out/test26.inter.out
./intervals_analysis ./demos/json/test27.json test > ./demos/inter_out/test27.inter.out
./intervals_analysis ./demos/json/test28.json test > ./demos/inter_out/test28.inter.out
./intervals_analysis ./demos/json/test29.json test > ./demos/inter_out/test29.inter.out
./intervals_analysis ./demos/json/test30.json test > ./demos/inter_out/test30.inter.out
./intervals_analysis ./demos/json/test31.json test > ./demos/inter_out/test31.inter.out
./intervals_analysis ./demos/json/test32.json test > ./demos/inter_out/test32.inter.out


